### ISSUE TITLE
Would you please add a license statement for this project?

### ISSUE THREAD

**Issue by warscape** [edave64/ED-Mahjong#1]
Would you please add a license statement for this project?
Thank you.

**Comment by edave64** [comment]
Done. Keep in mind that the files in the assets folder are taken from the KMahjong project and are subject to different copyright

**Comment by licaon-kter** [comment]
@edave64 link to the assets license?

**Comment by edave64** [comment]
@licaon-kter 

The tilesets all include licence information in the .copyright files

The backgrounds are all from https://cc0-textures.com/

I don't think the boards layouts are copyrightable. But they are all from kmahjongg

https://invent.kde.org/games/kmahjongg
